### ISSUE TITLE
System.Windows.Forms Library Repo Question.

### ISSUE THREAD

**Issue by slaee** [DanielVanNoord/System.Windows.Forms#3]
Where can I find the source repo of the System.Windows.Forms? cuz I want to have the latest version if ever there is...

**Comment by slaee** [comment]
I am glad that I found this repository, and wanted to contribute in dev. Would there be any manual how to build the System.Windows.Forms? so that I can add other objects from the latest dotnet winforms...

**Comment by DanielVanNoord** [comment]
It should just build like most dlls with .Net 6+ and/or Visual Studio. You can find a sample project that uses the nuget packages here: https://github.com/DanielVanNoord/Winforms-Cross. This is the source, it is derived from a part of mono.

**Comment by slaee** [comment]
> It should just build like most dlls with .Net 6+ and/or Visual Studio. You can find a sample project that uses the nuget packages here: https://github.com/DanielVanNoord/Winforms-Cross. This is the source, it is derived from a part of mono.

I've got it work, but sometimes WindowsExtension will not work, is there any a work around on this? I tried with TypeConverter for Image but toolstrip will give a lot of errors.

**Comment by DanielVanNoord** [comment]
Are you trying to load the image as an embedded resource? Some of that changed with .Net Core and I have found that they need to be loaded differently. If you can post a stack trace or even better a minimally viable project to demo the issue that would be very helpful.

**Comment by slaee** [comment]
> Are you trying to load the image as an embedded resource? Some of that changed with .Net Core and I have found that they need to be loaded differently. If you can post a stack trace or even better a minimally viable project to demo the issue that would be very helpful.

yeah here is what I got.

```
- In Image Class casting.

System.PlatformNotSupportedException : System.Windows.Extensions types are not supported on this platform.
```

and tried to fixed this with TypeConverter and works (System.Windows.Extensions is gone) but there's a new issue being raised in ToolStrips font:

```
Error Message:
   System.FormatException : Input string was not in a correct format.
  Stack Trace:

     at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Single.Parse(String s)
   at CodeChum.SimpleWordApp.FontSizeTextBox_TextChanged(Object sender, EventArgs e) in SimpleWordAppWithCustomeTypeConverter/SimpleWordApp/SimpleWordApp.cs:line 79
   at System.Windows.Forms.ToolStripItem.OnTextChanged(EventArgs e) in System.Windows.Forms/System.Windows.Forms/Controls/ToolStrips/ToolStripItem.cs:line 1250
   at System.Windows.Forms.ToolStripItem.set_Text(String value) in System.Windows.Forms/System.Windows.Forms/Controls/ToolStrips/ToolStripItem.cs:line 742
   at System.Windows.Forms.ToolStripControlHost.set_Text(String value) in System.Windows.Forms/System.Windows.Forms/Controls/ToolStrips/ToolStripControlHost.cs:line 220
   at CodeChum.SimpleWordApp..ctor() in SimpleWordAppWithCustomeTypeConverter/SimpleWordApp/SimpleWordApp.cs:line 21
   at CodeChum.Tests.SimpleWordAppTest..ctor() in SimpleWordAppWithCustomeTypeConverter/CodeChumUnitTest/CodeChumUnitTest.cs:line 26
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
```

**Comment by slaee** [comment]
> Are you trying to load the image as an embedded resource? Some of that changed with .Net Core and I have found that they need to be loaded differently. If you can post a stack trace or even better a minimally viable project to demo the issue that would be very helpful.


yeah here is what I got.

- In Image Class casting.
```
System.PlatformNotSupportedException : System.Windows.Extensions types are not supported on this platform.
```
and tried to fixed this with TypeConverter and works (System.Windows.Extensions is gone) but there's a new issue being raised in ToolStrips font:
```
Error Message:
   System.FormatException : Input string was not in a correct format.
  Stack Trace:

     at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Single.Parse(String s)
   at TestProject.SimpleWordApp.FontSizeTextBox_TextChanged(Object sender, EventArgs e) in SimpleWordAppWithCustomeTypeConverter/SimpleWordApp/SimpleWordApp.cs:line 79
   at System.Windows.Forms.ToolStripItem.OnTextChanged(EventArgs e) in System.Windows.Forms/System.Windows.Forms/Controls/ToolStrips/ToolStripItem.cs:line 1250
   at System.Windows.Forms.ToolStripItem.set_Text(String value) in System.Windows.Forms/System.Windows.Forms/Controls/ToolStrips/ToolStripItem.cs:line 742
   at System.Windows.Forms.ToolStripControlHost.set_Text(String value) in System.Windows.Forms/System.Windows.Forms/Controls/ToolStrips/ToolStripControlHost.cs:line 220
   at TestProject.SimpleWordApp..ctor() in SimpleWordAppWithCustomeTypeConverter/SimpleWordApp/SimpleWordApp.cs:line 21
   at TestClass.Tests.SimpleWordAppTest..ctor() in SimpleWordAppWithCustomeTypeConverter/UnitTest/UnitTest.cs:line 26
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
```
